# Generated by Django 2.2.14 on 2020-08-04 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UID', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=60)),
                ('Lastname', models.CharField(max_length=60)),
                ('MonthlyIncome', models.BigIntegerField()),
                ('DOB', models.DateField()),
                ('Phone', models.CharField(max_length=12)),
                ('LastUpdated', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('CashCheckingAccounts', models.BigIntegerField()),
                ('CashSavingsAccounts', models.BigIntegerField()),
                ('Securities', models.CharField(max_length=500)),
                ('PersonalProperty', models.CharField(max_length=60)),
                ('RealEstate', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('AppID', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('Loanamt', models.BigIntegerField()),
                ('Datefiled', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('Status', models.CharField(max_length=60)),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Users')),
            ],
        ),
    ]
