# Generated by Django 2.2.14 on 2020-09-05 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200904_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='CashCheckingAccounts',
        ),
        migrations.RemoveField(
            model_name='users',
            name='CashSavingsAccounts',
        ),
        migrations.RemoveField(
            model_name='users',
            name='MonthlyIncome',
        ),
        migrations.RemoveField(
            model_name='users',
            name='PersonalProperty',
        ),
        migrations.RemoveField(
            model_name='users',
            name='RealEstate',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Securities',
        ),
        migrations.AddField(
            model_name='application',
            name='Duration',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='Frequency',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='Installment',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='Type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Loanamt',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Status',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='Loandetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loantype', models.CharField(max_length=60, null=True)),
                ('Duration', models.BigIntegerField(null=True)),
                ('Address_HB', models.CharField(max_length=300, null=True)),
                ('Valuation_HB', models.BigIntegerField(null=True)),
                ('Dealer_VH', models.CharField(max_length=100, null=True)),
                ('Vehiclemake_VH', models.CharField(max_length=20, null=True)),
                ('Currentval_VH', models.BigIntegerField(null=True)),
                ('AppID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthlyIncome', models.BigIntegerField(null=True)),
                ('CashCheckingAccounts', models.BigIntegerField(null=True)),
                ('CashSavingsAccounts', models.BigIntegerField(null=True)),
                ('Securities', models.CharField(max_length=500, null=True)),
                ('PersonalProperty', models.CharField(max_length=60, null=True)),
                ('RealEstate', models.CharField(max_length=60, null=True)),
                ('AppID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Application')),
            ],
        ),
    ]
