# Generated by Django 2.2.14 on 2020-09-25 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200905_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ann_inc', models.BigIntegerField()),
                ('comp_bonds', models.BigIntegerField()),
                ('debt_mutual_funds', models.BigIntegerField()),
                ('reason', models.CharField(max_length=500)),
                ('AppID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Typea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ann_inc', models.BigIntegerField()),
                ('comp_bonds', models.BigIntegerField()),
                ('debt_mutual_funds', models.BigIntegerField()),
                ('equity_mutual_funds', models.BigIntegerField()),
                ('other_mutual_funds', models.BigIntegerField()),
                ('reason', models.CharField(max_length=500)),
                ('AppID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Application')),
            ],
        ),
    ]
