# Generated by Django 2.2.14 on 2020-12-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201201_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='CashCheckingAccounts',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='CashSavingsAccounts',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='MonthlyIncome',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='PersonalProperty',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='RealEstate',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='Securities',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='Address_HB',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='Currentval_VH',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='Dealer_VH',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='Duration',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='Loantype',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='Valuation_HB',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='Vehiclemake_VH',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
