# Generated by Django 2.2.14 on 2020-12-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201201_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandetails',
            name='Loantype',
        ),
    ]
