# Generated by Django 2.2.14 on 2020-12-01 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_loandetails_loantype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=10)),
                ('File', models.FileField(upload_to='')),
                ('AppID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Application')),
            ],
        ),
    ]
