# Generated by Django 2.2.14 on 2020-12-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_uploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='File',
        ),
    ]
