# Generated by Django 2.2.14 on 2020-12-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_uploads_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='File',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
