# Generated by Django 2.2.14 on 2020-12-04 13:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_uploads_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
    ]
