# Generated by Django 2.2.14 on 2020-12-07 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201204_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kycinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addrline1', models.CharField(max_length=500)),
                ('addrline2', models.CharField(blank=True, max_length=500, null=True)),
                ('PIN', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('caddrline1', models.CharField(max_length=500)),
                ('caddrline2', models.CharField(blank=True, max_length=500, null=True)),
                ('cPIN', models.CharField(max_length=10)),
                ('ccity', models.CharField(max_length=100)),
                ('cdistrict', models.CharField(max_length=100)),
                ('cstate', models.CharField(max_length=100)),
                ('AppID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Application')),
            ],
        ),
    ]
